# Generated by Django 3.1.7 on 2021-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_sessions', '0004_auto_20210423_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshsession',
            name='port',
            field=models.IntegerField(),
        ),
    ]
