# Generated by Django 3.1.7 on 2021-05-07 09:17

from django.db import migrations, models
import saved_sessions.models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_sessions', '0005_auto_20210423_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshsession',
            name='key_file',
            field=models.FileField(blank=True, upload_to=saved_sessions.models.RenamePath('ssh_keys/')),
        ),
        migrations.AlterField(
            model_name='sshsession',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
