# Generated by Django 3.1.7 on 2021-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_sessions', '0005_auto_20210423_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshsession',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
