# Generated by Django 3.1.7 on 2021-04-30 20:06

from django.db import migrations, models
import saved_sessions.models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_sessions', '0006_auto_20210430_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshsession',
            name='key_file',
            field=models.FileField(blank=True, upload_to=saved_sessions.models.RenamePath('ssh_keys/')),
        ),
    ]
