# Generated by Django 3.1.7 on 2021-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_sessions', '0007_sshsession_key_file'),
        ('saved_sessions', '0006_auto_20210507_0917'),
    ]

    operations = [
    ]
